/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.demo;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author yunus
 */
public class Game extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form Home
     */
    static String name = "BERNA KIRAZ";
    static int dimension = 8;
    static MultiLinkedList list = new MultiLinkedList();
    Node head = null;

    public Game(String name, int dimension) {
        initComponents();
        setLocationRelativeTo(null);
        this.name = name;
        this.dimension = dimension;
        lbl_name.setText(name);
        // arrange variable of game frame
        lbl_hamle.setText(String.valueOf(dimension * dimension));
        pnl_game.setLayout(new GridLayout(dimension, dimension));
        head = null;
        head = list.installHeader(head, dimension);
        head = list.installChild(head, dimension);
        head = list.deleteMiddleFour(head, dimension);
        // table method for create panel for button
        table(head, dimension);
        // for showing remaining to user
        list.remaining(head);

    }

    void table(Node head, int n) {
        // there is some ımage in packages.(pawn and blank).i couldnt arrange them to show their url at source packages teacher.So i added their screenshots in homework.
        // Hocam resimleri dosya yolunu vermeden eklemeye çalıştım fakat hata verdi her seferinde.
        int yStart = 49;
        int xStart = 'A';
        int i, j;
        char[] label = new char[2];
        for (i = 0; i < n; i++) {
            for (j = 0; j < n; j++) {
                label[0] = (char) (xStart + j);
                label[1] = (char) (yStart + i);
                if (list.exist(head, label) == 1) {
                    ImageIcon icon = new ImageIcon("C:\\Users\\yunus\\Documents\\NetBeansProjects\\demo\\src\\main\\java\\com\\mycompany\\demo\\pawn.png");
                    JButton b = new JButton(String.valueOf(label), icon);
                    b.setBackground(new Color(59, 89, 182));
                    b.setForeground(Color.WHITE);
                    b.setFocusPainted(false);
                    b.setBounds(50, 50, 50, 30);
                    b.addMouseListener(this);
                    Game.pnl_game.add(b);

                } else {
                    ImageIcon icon = new ImageIcon("C:\\Users\\yunus\\Documents\\NetBeansProjects\\demo\\src\\main\\java\\com\\mycompany\\demo\\X.png");
                    JButton b = new JButton(String.valueOf(String.valueOf(label)), icon);
                    b.setBounds(50, 50, 50, 30);
                    b.addMouseListener(this);
                    Game.pnl_game.add(b);

                }
            }
            System.out.print("\n");
        }
    }

    @Override
    public String getName() {
        return name;
    }

    public int getDimension() {
        return dimension;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_play = new javax.swing.JButton();
        lbl_hamle = new javax.swing.JLabel();
        lbl_hamle1 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        pnl_game = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        btn_play.setBackground(new java.awt.Color(255, 51, 51));
        btn_play.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btn_play.setForeground(new java.awt.Color(0, 0, 0));
        btn_play.setText("EXİT");
        btn_play.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });
        jPanel1.add(btn_play);
        btn_play.setBounds(870, 40, 110, 30);

        lbl_hamle.setBackground(new java.awt.Color(255, 255, 255));
        lbl_hamle.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lbl_hamle.setForeground(new java.awt.Color(0, 0, 0));
        lbl_hamle.setText("HAMLE:");
        jPanel1.add(lbl_hamle);
        lbl_hamle.setBounds(300, 40, 170, 30);

        lbl_hamle1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_hamle1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lbl_hamle1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_hamle1.setText("Possible hit location:");
        jPanel1.add(lbl_hamle1);
        lbl_hamle1.setBounds(540, 40, 260, 30);

        lbl_name.setBackground(new java.awt.Color(0, 0, 0));
        lbl_name.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(0, 0, 0));
        lbl_name.setText("UserName:");
        jPanel1.add(lbl_name);
        lbl_name.setBounds(20, 40, 170, 30);

        javax.swing.GroupLayout pnl_gameLayout = new javax.swing.GroupLayout(pnl_game);
        pnl_game.setLayout(pnl_gameLayout);
        pnl_gameLayout.setHorizontalGroup(
            pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        pnl_gameLayout.setVerticalGroup(
            pnl_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_game);
        pnl_game.setBounds(0, 80, 1000, 720);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("--");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 905, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1000, 30);

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\yunus\\Downloads\\background.jpg")); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(1000, 800));
        jLabel4.setMinimumSize(new java.awt.Dimension(1000, 800));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(1000, 800));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1000, 800);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(Game.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked
    int xx, xy;
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        setOpacity((float) 0.5);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        // TODO add your handling code here:
        setOpacity((float) 1.0);
    }//GEN-LAST:event_jPanel2MouseReleased

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        Home home = new Home();
        home.setVisible(true);
        home.pack();
        home.setLocationRelativeTo(null);
        home.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(false);


    }//GEN-LAST:event_btn_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game(name, dimension).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_play;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lbl_hamle;
    public static javax.swing.JLabel lbl_hamle1;
    private javax.swing.JLabel lbl_name;
    public static javax.swing.JPanel pnl_game;
    // End of variables declaration//GEN-END:variables
    JButton b = new JButton();
    char[] label = new char[2];
    char[] label2 = new char[2];
    char[] t1;
    char[] t2;

    int count = 0;

    @Override
    public void mouseClicked(MouseEvent e) {
        // for click on button.if count=0,it means you select one button.And then you select your target button.
        System.out.println("click");
        if (count == 0) {
            if (e.getButton() == MouseEvent.BUTTON1) {
                b = (JButton) e.getComponent(); // compare with panel.findComponentAt
                System.out.println("1." + b.getText());
            }
            for (int k = 0; k < b.getText().length(); k++) {
                label[k] = b.getText().charAt(k);
            }

            t1 = label;
            count++;
        } else {
            if (e.getButton() == MouseEvent.BUTTON1) {
                b = (JButton) e.getComponent(); // compare with panel.findComponentAt
                System.out.println("2." + b.getText());
            }
            for (int k = 0; k < b.getText().length(); k++) {
                label2[k] = b.getText().charAt(k);
            }

            t2 = label2;
            count--;
        }
        boolean flag = true;
        if (Arrays.toString(t1) != null) {
            if (list.exist(head, t1) == 1) {
                int b = list.possible(head, t1, dimension);
                if (b == 1) {
                    if (t2 != null) {
                        while (flag) {
                            System.out.print("Enter destination: ");
                            //&& t2[2] == '\0'
                            // Eger node bos ve alanin icer's'ndeyse
                            if (list.exist(head, t2) == 0 && (int) t2[0] <= 64 + dimension && (int) t2[0] > 64 && (int) t2[1] <= 48 + dimension && (int) t2[1] > 48) {
                                head = list.move(head, t1, t2, dimension);
                                System.out.print("\n");
                                list.table(head, dimension);
                                list.remaining(head);
                                pnl_game.removeAll();
                                table(head, dimension);
                                pnl_game.repaint();
                                flag = false;
                            } else {
                                System.out.print("Invalid Move\n");
                            }
                        }
                    } else {
                        return;
                    }
                } else {
                    count--;

                }
                System.out.print("\n");
            } else {
                System.out.print("Invalid source!\n");
                Game.lbl_hamle1.setText("Possible hit location: " + "Invalid source!");
            }

            t1 = null;
            t2 = null;
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
        System.out.print("");
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        System.out.print("");
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        System.out.print("");
    }

    @Override
    public void mouseExited(MouseEvent e) {
        System.out.print("");

    }

}
